### ISSUE TITLE
checkm failed

### ISSUE THREAD

**Issue by hoelzer** [phiweger/isolate_pe#2]
executor >  google-lifesciences (29)
[4c/32a6aa] process > assembly (9) [ 44%] 8 of 18
[bb/faf6fc] process > annotate (8) [ 25%] 2 of 8
[d7/225171] process > checkm (3)   [ 38%] 3 of 8, failed: 1
Error executing process > 'checkm (3)'

Caused by:
  Process `checkm (3)` terminated with an error exit status (1)

Command executed:

  mkdir tmp
  mkdir input
  mv ERR3192629.fasta input/assembly.fa
  checkm lineage_wf --tmpdir tmp --pplacer_threads 4 -t 8 --reduced_tree -x fa input ERR3192629_checkm > summary.txt
  checkm tree_qa ERR3192629_checkm > taxonomy.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
      Finished aligning 10 of 43 (23.26%) marker genes.
      Finished aligning 11 of 43 (25.58%) marker genes.
      Finished aligning 12 of 43 (27.91%) marker genes.
      Finished aligning 13 of 43 (30.23%) marker genes.
      Finished aligning 14 of 43 (32.56%) marker genes.
      Finished aligning 15 of 43 (34.88%) marker genes.
      Finished aligning 16 of 43 (37.21%) marker genes.
      Finished aligning 17 of 43 (39.53%) marker genes.
      Finished aligning 18 of 43 (41.86%) marker genes.
      Finished aligning 19 of 43 (44.19%) marker genes.
      Finished aligning 20 of 43 (46.51%) marker genes.
      Finished aligning 21 of 43 (48.84%) marker genes.
      Finished aligning 22 of 43 (51.16%) marker genes.
      Finished aligning 23 of 43 (53.49%) marker genes.
      Finished aligning 24 of 43 (55.81%) marker genes.
      Finished aligning 25 of 43 (58.14%) marker genes.
      Finished aligning 26 of 43 (60.47%) marker genes.
      Finished aligning 27 of 43 (62.79%) marker genes.
      Finished aligning 28 of 43 (65.12%) marker genes.
      Finished aligning 29 of 43 (67.44%) marker genes.
      Finished aligning 30 of 43 (69.77%) marker genes.
      Finished aligning 31 of 43 (72.09%) marker genes.
      Finished aligning 32 of 43 (74.42%) marker genes.
      Finished aligning 33 of 43 (76.74%) marker genes.
      Finished aligning 34 of 43 (79.07%) marker genes.
      Finished aligning 35 of 43 (81.40%) marker genes.
      Finished aligning 36 of 43 (83.72%) marker genes.
      Finished aligning 37 of 43 (86.05%) marker genes.
      Finished aligning 38 of 43 (88.37%) marker genes.
      Finished aligning 39 of 43 (90.70%) marker genes.
      Finished aligning 40 of 43 (93.02%) marker genes.
      Finished aligning 41 of 43 (95.35%) marker genes.
      Finished aligning 42 of 43 (97.67%) marker genes.
      Finished aligning 43 of 43 (100.00%) marker genes.
  Killed
  Uncaught exception: Sys_error("ERR3192629_checkm/storage/tree/concatenated.pplacer.json: No such file or directory")
  Fatal error: exception Sys_error("ERR3192629_checkm/storage/tree/concatenated.pplacer.json: No such file or directory")
      Finished parsing hits for 1 of 1 (100.00%) bins.
  Traceback (most recent call last):
    File "/opt/conda/bin/checkm", line 611, in <module>
      checkmParser.parseOptions(args)
    File "/opt/conda/lib/python3.7/site-packages/checkm/main.py", line 859, in parseOptions
      self.lineageSet(options)
    File "/opt/conda/lib/python3.7/site-packages/checkm/main.py", line 215, in lineageSet
      resultsParser, options.unique, options.multi)
    File "/opt/conda/lib/python3.7/site-packages/checkm/treeParser.py", line 485, in getBinMarkerSets
      tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
    File "/opt/conda/lib/python3.7/site-packages/dendropy/datamodel/basemodel.py", line 216, in get_from_path
      with open(src, "r", newline=None) as fsrc:
  FileNotFoundError: [Errno 2] No such file or directory: 'ERR3192629_checkm/storage/tree/concatenated.tre'

**Comment by phiweger** [comment]
has this gone away @hoelzer ?

**Comment by hoelzer** [comment]
yep seems so
